[tool.black]
line-length = 120

[tool-isort]
src_paths = ["chatbot"]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
force_single_line = true
force_sort_within_sections = true
lexicographical = true
line_length = 120

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-semiprivate = false
ignore-private = false
ingnore-property-decorators = false
ignore-module = true
fail-under = 100
exclude = ["setup.py"]
color = true
